export const Data = [
    {
      q: "What does CMOS stand for?",
      a: "Complementary Metal Oxide Semiconductor",
      b: "Complementary Metal Oxide System",
      c: "Computational Metal Oxide Semiconductor",
      d: "Complementary Machine Overlap Semiconductor",
      ans: "Complementary Metal Oxide Semiconductor" ,
    },
    {
      q: "CMOS logic gates are commonly used in which of the following applications?",
      a: " High-frequency analog circuits",
      b: "Power amplifiers",
      c: "Digital integrated circuits",
      d: "RF amplifiers",
      ans: "Digital integrated circuits",
    },
    {
      q: "What is the typical voltage range for CMOS circuits?",
      a: " Output is HIGH",
      b: "Output is LOW",
      c: "Output is floating",
      d: " Output is undefined",
      ans: "Output is LOW",
    },

 {
      q: "Which component is used to design logic gates in CMOS technology?",
      a: "Capacitors",
      b: "Inductors",
      c: "Resistors",
      d: "Transistorsr",
      ans: "Transistors" ,
    },
    {
      q: "In CMOS technology, what causes power dissipation in the steady-state condition?",
      a: " Dynamic power",
      b: "Static power",
      c: " Switching losses",
      d: " Capacitive load charging",
      ans: "Static power",
    },
    {
      q: "What happens if you increase the number of transistors in a CMOS logic circuit?",
      a: " Increases power dissipation",
      b: "Decreases switching time",
      c: "Increases the area required on the chip",
      d: " Reduces the overall voltage",
      ans: "Increases the area required on the chip",
    },

{
      q: "What is a primary reason for using CMOS technology in microprocessors?",
      a: "High current drive",
      b: "High voltage operation",
      c: " Low standby power consumption",
      d: "High clock speed",
      ans: " Low standby power consumption" ,
    },
    {
      q: "What is the main advantage of CMOS over older technologies like TTL?",
      a: "Higher power consumption",
      b: " Lower power consumption",
      c: "Slower speed",
      d: " Higher voltage requirement",
      ans: " Lower power consumption",
    },
    {
      q: "Which of the following is NOT a characteristic of CMOS technology?",
      a: " Low power consumption",
      b: " High noise margin",
      c: "High-speed operation",
      d: "  High static power dissipation",
      ans: " High static power dissipation",
    },

{
      q: "What is the state of the output of a CMOS NAND gate when both inputs are HIGH?",
      a: " HIGH",
      b: " LOW",
      c: "  Floating",
      d: "Undefined",
      ans: "  LOW" ,
    },
    {
      q: "Which of the following is true about CMOS circuits when the input signal changes?",
      a: "There is no power consumption.",
      b: " Power consumption occurs during switching.",
      c: "Power consumption is constant.",
      d: " Power consumption is maximum at steady state.",
      ans: " Power consumption occurs during switching.",
    },
    {
      q: " Which type of transistor is used in CMOS circuits to pull the output to a low state?",
      a: " P-type",
      b: " N-type",
      c: " Bipolar",
      d: " FET",
      ans: " N-type",
    },

  ];